### ISSUE TITLE
Using Only 1 Controller Causes Log Spam

### ISSUE THREAD

**Issue by WasabiIceCream** [Hotrian/OpenVRTwitchChat#13]
Easy to replicate the issue, just launch the app with only 1 controller active.
It causes the app to search for controller, find one, and repeat over and over until it detects a second controller.
Can be fixed by just turning on the second controller at any point.

![twitchchatoverlay](https://cloud.githubusercontent.com/assets/12481327/16925014/22f5ab9e-4cf0-11e6-95f2-23ae031fe5cf.PNG)

**Comment by Hotrian** [comment]
Will fix, thanks for the bug report.

**Comment by Hotrian** [comment]
Infact this was fixed in e42a47c58d5e0fcb330f9ef2dcdd2b43a30b1bdd but that was after v1.0.4 which is the recommended version currently due to the buggy Emote support ;] I will see about updating v1.0.4 to perhaps v1.0.4.1 or so. Sorry for the inconvenience :o.

**Comment by Hotrian** [comment]
Okay, this should be fixed in [v1.0.6b](https://github.com/Hotrian/OpenVRTwitchChat/releases/tag/v1.0.6b-beta), which should include all of the changes from v1.0.5 and v1.0.6, except for Emote support.

This one still spams for a few seconds on startup if _no_ controllers are detected but correctly stops complaining after it finds at least one controller in my testing :)

Let me know if v1.0.6b doesn't fix this for you for some reason though.
