### ISSUE TITLE
Login anonymously

### ISSUE THREAD

**Issue by ocgineer** [Hotrian/OpenVRTwitchChat#19]
As you have no way to reply back (yet) in chat it might be easier for people to login to the Twitch Chat anonymously, or have an option to login like that. The username needs to be 'justinfan' followed by a few random numbers. The password can then be blank or random.

**Comment by Hotrian** [comment]
Thanks for the tip! I didn't see that anywhere in the API documentation. Are you sure you can connect to the IRC that way?

**Comment by Hotrian** [comment]
Cool, thanks for the info.

I'll probably add this to my implementation in [OpenVRDesktopDisplayPortal](https://github.com/Hotrian/OpenVRDesktopDisplayPortal), but if you check #18 you'll see I probably won't be working on this repo in particular anymore. OVRDDP is due for a name change and I will be making it into more of a general purpose VR Utility program, and OVRTC will fit right in as a selectable mode :).

I might make a few changes to OVRTC before dropping updates to this repo, but OVRDDP's Overlay implementation has a lot of enhancements that would be a pain to reimplement into OVRTC at this point. It would be much easier to add OVRTC as a mode to OVRDDP and change the name :).

I realize that might make it a bit harder for new devs to work on, but for the end users it will be easier to just download a single program and switch between modes rather than managing updating two (or more) programs and keeping track of all the shortcuts, etc.

**Comment by Hotrian** [comment]
Also, yes: I did add an artificial requirement that you _need_ a password, because I wasn't aware there was a situation where you didn't :P

**Comment by ocgineer** [comment]
Yea saw that comment, and of course have a look at it as well. Just wanted to point out that it was possible to login anonymously as it might save some hassle for both you and the end user.

The AboveFlipped chat mode is genius btw ;)

**Comment by Hotrian** [comment]
Hey, I had to make some changes for the latest Twitch API, so I went ahead and added this. If you leave the Username or OAuth box blank OVRTC will generate a "JustinFan#####" username and let you login anonymously, so it is now no longer required to use a Username or OAuth to login.

Unfortunately, I misplaced the source for the "b" version that was missing Emote support. On the upside though, it seems it was Unity 5.3.5f1 that had issues with the Emote support, and Unity 5.3.6f1 seems to not have the issues with Emote support anymore that caused the chat to freeze for some reason.

Unfortunately, it seems Unity 5.3.6f1 bugged out the sounds, and they play initially but sometimes they stop playing and won't play again. I'll have to look into this some more.
