### ISSUE TITLE
Can't show chat on stream (no Display Mirror)

### ISSUE THREAD

**Issue by Cunningcory** [Hotrian/OpenVRTwitchChat#37]
I don't think Display Mirror exists anymore as a VR window. I'm streaming Half Life: Alyx and just starting using this app! The overlay is not streamed, however. There's no "display mirror" to use instead of the game output.

**Comment by Hotrian** [comment]
You are correct - Valve has renamed this to `VR View`.

Right click SteamVR in the System Tray (bottom right of your screen normally, by the clock) and click `Display VR View`

![image](https://i.imgur.com/A4DxrhL.png)

I don't have my Headset connected, but you may find it opens docked to the main SteamVR window like this 

![image](https://i.imgur.com/U6E9HlC.png)

Note the top part is the normal SteamVR Status window, and the bottom part is the VR View. Since you want to stream this window, click the Undock button

![image](https://i.imgur.com/cSUk3U1.png)

This will open a dedicated window which you can copy to your stream, you will get a window like this

![image](https://i.imgur.com/OtrldJ2.png)

However please note again I do not have my VR Headset connected (I put it away when not in use because I have cats who would eventually knock it off my desk). You should see the same image on this window as you see in your headset. If you go to `Menu` in the top left you can select which eye is being shown, and you can fullscreen it on the top right.

**Comment by Hotrian** [comment]
Please note the `Non-Issue` tag is not meant as disrespect. I understand completely that this is an issue for you and your stream - the tag only means that it's not something that can be (or should be, in some cases) changed within OVRTC. This has to do with how SteamVR works, not OVRTC itself.

**Comment by Cunningcory** [comment]
Thanks for your quick reply. Using the VR View allows for the overlay to be seen! This does, unfortunately, negate some of the conveniences HL: Alyx is doing on their desktop view (displaying health, ammo, etc. stats and giving a loading screen when loading), so I'll just have to decide which trade-off I'd like to have. Thanks again!
