### ISSUE TITLE
unfamiliar with OAuth

### ISSUE THREAD

**Issue by MagusHouse** [Hotrian/OpenVRTwitchChat#38]
this is the first time I'm using a 3rd party app with Twitch, so I don't know how to use OAuth with your app to sign in to my account. What specifically am I supposed to put in the OAuth Key field?

**Comment by Hotrian** [comment]
An OAuth is like an app specific password. You should never use your actual twitch password to log into apps or services which you don’t completely trust — as such, I went the OAuth route to give peace of mind. An OAuth provides limited access to your account, and cannot do things such as delete your account, which an app otherwise may be able to do with your actual login credentials. In specific, OVRTC requires the IRC permission, so you need to use an OAuth with that permission. You can get your OAuth at this link which is posted in the readme: http://www.twitchapps.com/tmi/

This will allow OVRTC to connect to your chat as you, so you won’t effect your viewer count. If you prefer, you actually don’t have to enter anything into the username/password field, and then you’ll connect to your chat as an anonymous user (JustinFan####, last I checked), but this will increase your viewer count by 1. I’ve had reports that the viewer count broke for some users, so this may not effect you at all. 

OVRTC will not save the password entered for security reasons, so it’s faster if you just log in anonymously.

**Comment by MagusHouse** [comment]
thank you so much, I had no idea how to get an OAuth Key and the Twitch main site wasn't helping whatsoever! This worked perfectly
