### ISSUE TITLE
Lagging really bad

### ISSUE THREAD

**Issue by RealityEclipse** [Hotrian/OpenVRTwitchChat#39]
Whenever I go to look at chat, or if I just go close to looking behind my right controller my game has serious and unplayable frame drops. For example, HL:A. Unplayable when I go to look at chat and when I quit OpenVRTwitchChat it performs just fine.

**Comment by Hotrian** [comment]
Hmm. I can’t think of any reason that would happen. 

Could you attach the output_log.txt from inside the Data folder? Could you also post a screenshot of your frame timings according to SteamVR?

**Comment by RealityEclipse** [comment]
[output_log.txt](https://github.com/Hotrian/OpenVRTwitchChat/files/4409135/output_log.txt)
I'll have to get the frame timings next time I play.

**Comment by Hotrian** [comment]
Thanks for the log. Unfortunately nothing worthy of note in that log except the `410` error code returned by Twitch, which is mentioned in #32. This is why the viewer count no longer works, but doesn't actually effect the chat, and shouldn't cause any lag - especially not a lag which was intensified when looking at the overlay vs not.

OVRTC is pretty lightweight, but is it possible your CPU is overloaded and OVRTC is just the [straw that breaks the camels back](https://en.wikipedia.org/wiki/Straw_that_broke_the_camel%27s_back), so to speak? Aside from an error being thrown that's the only thing I can think of.

Are you minimizing OVRTC's window? It was mentioned at the end of #28 that minimizing the window causes a lot of CPU usage (probably due to Unity throwing the framerate as high as possible when minimized). I would recommend not minimizing it, in that case, until the issue can be addressed.

**Comment by RealityEclipse** [comment]
I did make sure that it wasn't minimized since I read that before posting this. Doesn't actually do anything for me.

**Comment by Hotrian** [comment]
I am closing this one for being stale. If this is still happening please reopen this issue.
